const songData = [
  {
    id: 1,
    title: "Intro",
    artist: "Chloe x Halle",
    album: "Ungodly Hour",
    duration: "1:20",
  },
  {
    id: 2,
    title: "Forgive Me",
    artist: "Chloe x Halle",
    album: "Ungodly Hour",
    duration: "2:54",
  },
  {
    id: 3,
    title: "Baby Girl",
    artist: "Chloe x Halle",
    album: "Ungodly Hour",
    duration: "3:01",
  },
  {
    id: 4,
    title: "Do It",
    artist: "Chloe x Halle",
    album: "Ungodly Hour",
    duration: "2:58",
  },
  {
    id: 5,
    title: "Tipsy",
    artist: "Chloe x Halle",
    album: "Ungodly Hour",
    duration: "2:50",
  },
  {
    id: 6,
    title: "Ungodly Hour",
    artist: "Chloe x Halle",
    album: "Ungodly Hour",
    duration: "3:38",
  },
  {
    id: 7,
    title: "Busy Boy",
    artist: "Chloe x Halle",
    album: "Ungodly Hour",
    duration: "2:48",
  },
  {
    id: 8,
    title: "Catch Up (feat. Swae Lee)",
    artist: "Chloe x Halle",
    album: "Ungodly Hour",
    duration: "2:43",
  },
  {
    id: 9,
    title: "Overwhelmed",
    artist: "Chloe x Halle",
    album: "Ungodly Hour",
    duration: "3:34",
  },
  {
    id: 10,
    title: "Lonely",
    artist: "Chloe x Halle",
    album: "Ungodly Hour",
    duration: "3:32",
  },
  {
    id: 11,
    title: "Don't Make It Harder on Me",
    artist: "Chloe x Halle",
    album: "Ungodly Hour",
    duration: "2:43",
  },
  {
    id: 12,
    title: "Wonder What She Thinks of Me",
    artist: "Chloe x Halle",
    album: "Ungodly Hour",
    duration: "3:11",
  },
  {
    id: 13,
    title: "ROYL",
    artist: "Chloe x Halle",
    album: "Ungodly Hour",
    duration: "3:39",
  },
  {
    id: 14,
    title: "Pray You Catch Me",
    artist: "Beyonce",
    album: "Lemonade",
    duration: "3:16",
  },

  {
    id: 15,
    title: "Hold Up",
    artist: "Beyonce",
    album: "Lemonade",
    duration: "3:41",
  },
  {
    id: 16,
    title: "Don't Hurt Yourself",
    artist: "Beyonce",
    album: "Lemonade",
    duration: "3:54",
  },
  {
    id: 17,
    title: "Sorry",
    artist: "Beyonce",
    album: "Lemonade",
    duration: "3:53",
  },
  {
    id: 18,
    title: "6 Inch",
    artist: "Beyonce",
    album: "Lemonade",
    duration: "4:20",
  },
  {
    id: 19,
    title: "Daddy Lessons",
    artist: "Beyonce",
    album: "Lemonade",
    duration: "4:48",
  },
  {
    id: 20,
    title: "Love Drought",
    artist: "Beyonce",
    album: "Lemonade",
    duration: "3:57",
  },
  {
    id: 21,
    title: "Sandcastles",
    artist: "Beyonce",
    album: "Lemonade",
    duration: "3:03",
  },
  {
    id: 22,
    title: "Forward",
    artist: "Beyonce",
    album: "Lemonade",
    duration: "1:19",
  },
  {
    id: 23,
    title: "Freedom",
    artist: "Beyonce",
    album: "Lemonade",
    duration: "4:50",
  },
  {
    id: 24,
    title: "All Night",
    artist: "Beyonce",
    album: "Lemonade",
    duration: "5:22",
  },
  {
    id: 25,
    title: "Formation",
    artist: "Beyonce",
    album: "Lemonade",
    duration: "3:26",
  },
  {
    id: 26,
    title: "Future Nostalgia",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: "3:04",
  },
  {
    id: 27,
    title: "Don't Start Now",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: "3:03",
  },
  {
    id: 28,
    title: "Cool",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: "3:29",
  },
  {
    id: 29,
    title: "Physical",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: "3:14",
  },
  {
    id: 30,
    title: "Levitating",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: "3:23",
  },
  {
    id: 31,
    title: "Pretty Please",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: "3:14",
  },
  {
    id: 32,
    title: "Hallucinate",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: "3:28",
  },
  {
    id: 33,
    title: "Love Again",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: "4:18",
  },
  {
    id: 34,
    title: "Break My Heart",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: "3:41",
  },
  {
    id: 35,
    title: "Good in Bed",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: "3:38",
  },
  {
    id: 36,
    title: "Boys Will Be Boys",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: "2:46",
  },
  {
    id: 37,
    title: "Crazy in Love",
    artist: "Beyonce",
    album: "Crazy in Love",
    duration: "3:56",
  },
  {
    id: 38,
    title: "Naughty Girl",
    artist: "Beyonce",
    album: "Crazy in Love",
    release_date: "2004-03-14",
    duration: "3:28",
  },
  {
    id: 39,
    title: "Baby Boy",
    artist: "Beyonce",
    album: "Crazy in Love",
    release_date: "2003-08-03",
    duration: "4:04",
  },
  {
    id: 40,
    title: "Hip Hop Star",
    artist: "Beyonce",
    album: "Crazy in Love",
    release_date: "2004-02-23",
    duration: "3:42",
  },
  {
    id: 41,
    title: "Be with You",
    artist: "Beyonce",
    album: "Crazy in Love",
    release_date: "2003-07-01",
    duration: "4:20",
  },
  {
    id: 42,
    title: "Me, Myself and I",
    artist: "Beyonce",
    album: "Crazy in Love",
    release_date: "2003-09-01",
    duration: "5:01",
  },
  {
    id: 43,
    title: "Yes",
    artist: "Beyonce",
    album: "Crazy in Love",
    release_date: "2004-06-01",
    duration: "4:19",
  },
  {
    id: 44,
    title: "Signs",
    artist: "Beyonce",
    album: "Crazy in Love",
    release_date: "2005-02-13",
    duration: "3:55",
  },
];

module.exports = { songData };
